/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.espe.edu.GeographicInnformationSystem.view;

import ec.espe.edu.GeographicInnformationSystem.controller.ScaleController;
import ec.espe.edu.GeographicInnformationSystem.controller.GeographicCoordenateController;
import ec.espe.edu.GeographicInnformationSystem.controller.UtmCoordenateController;
import ec.espe.edu.GeographicInnformationSystem.model.GeographicCoordenate;
import ec.espe.edu.GeographicInnformationSystem.model.Scale;
import ec.espe.edu.GeographicInnformationSystem.model.UtmCoordenate;
import javax.swing.JOptionPane;
import static javax.swing.Spring.scale;

/**
 *
 * @author Domenica
 */
public class frmGeographicCoordenate extends javax.swing.JFrame {

    /**
     * Creates new form frmGeographicCoordenate
     */
    public frmGeographicCoordenate() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtLongitude = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtLatitude = new javax.swing.JTextField();
        btnCalculate = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtShowGeographicCoordinate = new javax.swing.JTextArea();
        btnShow = new javax.swing.JButton();
        txtshowUtmCoordenates = new javax.swing.JTextField();
        btnutmCoordenates = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtMeridian = new javax.swing.JTextField();
        txtParalel = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtScale = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtCalculateTheScale = new javax.swing.JTextArea();
        btnCalculateScale = new javax.swing.JButton();
        btnShowScale = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtMeridianCm = new javax.swing.JTextField();
        txtParalelCm = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Bright", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 102, 0));
        jLabel1.setText("Geographic Coordenates System ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 0));
        jLabel2.setText("╔╩═══════════════════════╩═══════════════════════╩╗");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 0));
        jLabel3.setText("╚╦═══════════════════════╦══════════════════════╦╝");

        jLabel4.setFont(new java.awt.Font("Eras Light ITC", 1, 12)); // NOI18N
        jLabel4.setText("Enter Longitude in cm:");

        txtLongitude.setFont(new java.awt.Font("Eras Light ITC", 0, 12)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Eras Light ITC", 1, 12)); // NOI18N
        jLabel5.setText("Enter Latitude in cm:");

        txtLatitude.setFont(new java.awt.Font("Eras Light ITC", 0, 12)); // NOI18N

        btnCalculate.setFont(new java.awt.Font("Eras Light ITC", 0, 12)); // NOI18N
        btnCalculate.setText("Calculate Geographic Coordenates");
        btnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateActionPerformed(evt);
            }
        });

        txtShowGeographicCoordinate.setColumns(20);
        txtShowGeographicCoordinate.setFont(new java.awt.Font("Eras Light ITC", 0, 12)); // NOI18N
        txtShowGeographicCoordinate.setRows(5);
        jScrollPane1.setViewportView(txtShowGeographicCoordinate);

        btnShow.setFont(new java.awt.Font("Eras Light ITC", 0, 12)); // NOI18N
        btnShow.setText("Show Geographic Coordanates");
        btnShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowActionPerformed(evt);
            }
        });

        txtshowUtmCoordenates.setFont(new java.awt.Font("Eras Light ITC", 0, 12)); // NOI18N

        btnutmCoordenates.setFont(new java.awt.Font("Eras Light ITC", 0, 12)); // NOI18N
        btnutmCoordenates.setText("Show UTM Coordenates");
        btnutmCoordenates.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnutmCoordenatesActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Eras Light ITC", 1, 12)); // NOI18N
        jLabel6.setText("Enter Meridian UTM :");

        jLabel7.setFont(new java.awt.Font("Eras Light ITC", 1, 12)); // NOI18N
        jLabel7.setText("Enter Paralel UTM :");

        txtMeridian.setFont(new java.awt.Font("Eras Light ITC", 0, 12)); // NOI18N

        txtParalel.setFont(new java.awt.Font("Eras Light ITC", 0, 12)); // NOI18N

        btnSave.setFont(new java.awt.Font("Eras Light ITC", 0, 12)); // NOI18N
        btnSave.setText("Calculate UTM coordenates");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Eras Light ITC", 1, 12)); // NOI18N
        jLabel8.setText("Enter the scale:");

        txtScale.setFont(new java.awt.Font("Eras Light ITC", 0, 12)); // NOI18N
        txtScale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtScaleActionPerformed(evt);
            }
        });

        txtCalculateTheScale.setColumns(20);
        txtCalculateTheScale.setFont(new java.awt.Font("Eras Light ITC", 0, 12)); // NOI18N
        txtCalculateTheScale.setRows(5);
        jScrollPane2.setViewportView(txtCalculateTheScale);

        btnCalculateScale.setFont(new java.awt.Font("Eras Light ITC", 0, 12)); // NOI18N
        btnCalculateScale.setText("Calculate Scale");
        btnCalculateScale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateScaleActionPerformed(evt);
            }
        });

        btnShowScale.setFont(new java.awt.Font("Eras Light ITC", 0, 12)); // NOI18N
        btnShowScale.setText("Show Scale");
        btnShowScale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowScaleActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Eras Light ITC", 1, 12)); // NOI18N
        jLabel9.setText("Enter Meridian cm UTM :");

        jLabel10.setFont(new java.awt.Font("Eras Light ITC", 1, 12)); // NOI18N
        jLabel10.setText("Enter Paralel cm UTM :");

        txtMeridianCm.setFont(new java.awt.Font("Eras Light ITC", 0, 12)); // NOI18N

        txtParalelCm.setFont(new java.awt.Font("Eras Light ITC", 0, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtLongitude, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLatitude, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnShow)
                .addGap(103, 103, 103))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(166, 166, 166))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(225, 225, 225))))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addGap(191, 191, 191)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtMeridian, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMeridianCm, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtParalel, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtParalelCm, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel8)
                                .addGap(124, 124, 124)
                                .addComponent(txtScale, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(6, 6, 6)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnutmCoordenates)
                                .addGap(71, 71, 71))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnCalculate)
                                    .addComponent(btnSave))
                                .addGap(18, 18, 18)
                                .addComponent(txtshowUtmCoordenates, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(35, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(btnCalculateScale)
                        .addGap(72, 72, 72)
                        .addComponent(jScrollPane2)
                        .addGap(23, 23, 23))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnShowScale)
                .addGap(126, 126, 126))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel4)
                                            .addComponent(txtLongitude, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(44, 44, 44)
                                        .addComponent(btnCalculate)))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(txtLatitude, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnShow)))
                        .addGap(66, 66, 66)
                        .addComponent(jLabel6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9)
                                .addGap(43, 43, 43)
                                .addComponent(jLabel10)
                                .addGap(16, 16, 16))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtshowUtmCoordenates, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                                    .addComponent(btnSave))
                                .addGap(18, 18, 18)
                                .addComponent(btnutmCoordenates))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtMeridian, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(txtParalel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtMeridianCm, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtParalelCm, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtScale, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCalculateScale))
                        .addGap(70, 70, 70))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnShowScale)
                        .addGap(26, 26, 26))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed

        float longitude;
        float latitude;
        int longitudeGrade = 78;
        float minutesLongitude;
        float decimalPartLongitude;
        float wholePartLongitude;
        float secondsLongitude;
        float latitudeGrade = 0;
        float minutesLatitude;
        float decimalPartLatitude;
        float wholePartLatitude;
        float secondsLatitude;
        GeographicCoordenateController geographicCoordenateController = new GeographicCoordenateController();
        GeographicCoordenate geographicCoordenate;

        longitude = Float.parseFloat(txtLongitude.getText());
        latitude = Float.parseFloat(txtLatitude.getText());

        geographicCoordenate = new GeographicCoordenate(longitude, latitude);
        geographicCoordenateController.save(geographicCoordenate);
        minutesLongitude = geographicCoordenateController.calculateMinutesLongitude(longitude);
        decimalPartLongitude = geographicCoordenateController.calculateDecimalPartLongitude(minutesLongitude);

        wholePartLongitude = geographicCoordenateController.calculateWholePartLongitude(minutesLongitude, decimalPartLongitude);
        secondsLongitude = geographicCoordenateController.calculateSecondsLongitude(decimalPartLongitude);
        minutesLatitude = geographicCoordenateController.calculateMinutesLatitude(latitude);
        decimalPartLatitude = geographicCoordenateController.calculateDecimalPartLatitude(minutesLatitude);
        secondsLatitude = geographicCoordenateController.calculateSecondsLatitude(decimalPartLatitude);
        wholePartLatitude = geographicCoordenateController.calculateWholaPartLatitude(minutesLatitude, decimalPartLatitude);
        JOptionPane.showMessageDialog(rootPane, "longitude is --> " + longitudeGrade + "° " + secondsLongitude + "' " + wholePartLongitude + "'' " + "O" + "\n" + "latitude is --> " + latitudeGrade + "° " + wholePartLatitude + "' " + secondsLatitude + "'' " + "S");

    }//GEN-LAST:event_btnCalculateActionPerformed

    private void btnShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowActionPerformed
        GeographicCoordenateController geographicCoordenateController = new GeographicCoordenateController();
        txtShowGeographicCoordinate.setText(geographicCoordenateController.read());


    }//GEN-LAST:event_btnShowActionPerformed

    private void btnutmCoordenatesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnutmCoordenatesActionPerformed

        UtmCoordenateController utmCoordenateController = new UtmCoordenateController();
        txtshowUtmCoordenates.setText(utmCoordenateController.read());
    }//GEN-LAST:event_btnutmCoordenatesActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        UtmCoordenate utmCoordenate;
        float utmMeridian;
        float utmParalel;
        float utmMeridianCm;
        float utmParalelCm;
        float meridian;
        float paralel;
        float meridianCm;
        float paralelCm;
        float meridianCoordenate;
        float paralelCoordenate;

        UtmCoordenateController utmCoordenateController = new UtmCoordenateController();

        utmMeridian = Float.parseFloat(txtMeridian.getText());
        utmParalel = Float.parseFloat(txtParalel.getText());
        utmMeridianCm = Float.parseFloat(txtMeridianCm.getText());
        utmParalelCm = Float.parseFloat(txtParalelCm.getText());

        meridian = utmCoordenateController.calculateUtmMeridian(utmMeridian);
        paralel = utmCoordenateController.calculateUtmParalel(utmParalel);
        meridianCm = utmCoordenateController.calculateUtmMeridianCm(utmMeridianCm);
        paralelCm = utmCoordenateController.calculateUtmParalelCm(utmParalelCm);
        meridianCoordenate = meridian + meridianCm;
        paralelCoordenate = paralel + paralelCm;
        
        JOptionPane.showMessageDialog(rootPane, meridianCoordenate + " X" + "\n" + paralelCoordenate + " Y");


    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnCalculateScaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateScaleActionPerformed
        int finalScale;
        int scaleTransformation;
        Scale scale;

        ScaleController scaleController = new ScaleController();

        finalScale = Integer.parseInt(txtScale.getText());

        scaleTransformation = scaleController.calculateScale(finalScale);

        JOptionPane.showMessageDialog(rootPane, "The scale 1: " + finalScale + " means 1cm in the map is " + scaleTransformation + " m in the reality ");
        //JOptionPane.showMessageDialog(rootPane, scale.getScale());
    }//GEN-LAST:event_btnCalculateScaleActionPerformed

    private void btnShowScaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowScaleActionPerformed
        ScaleController calculateScaleController = new ScaleController();
        txtCalculateTheScale.setText(calculateScaleController.read());
    }//GEN-LAST:event_btnShowScaleActionPerformed

    private void txtScaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtScaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtScaleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmGeographicCoordenate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmGeographicCoordenate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmGeographicCoordenate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmGeographicCoordenate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmGeographicCoordenate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculate;
    private javax.swing.JButton btnCalculateScale;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnShow;
    private javax.swing.JButton btnShowScale;
    private javax.swing.JButton btnutmCoordenates;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtCalculateTheScale;
    private javax.swing.JTextField txtLatitude;
    private javax.swing.JTextField txtLongitude;
    private javax.swing.JTextField txtMeridian;
    private javax.swing.JTextField txtMeridianCm;
    private javax.swing.JTextField txtParalel;
    private javax.swing.JTextField txtParalelCm;
    private javax.swing.JTextField txtScale;
    private javax.swing.JTextArea txtShowGeographicCoordinate;
    private javax.swing.JTextField txtshowUtmCoordenates;
    // End of variables declaration//GEN-END:variables

}
