/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.espe.edu.GeographicInnformationSystem.view;

import ec.espe.edu.GeographicInnformationSystem.controller.GeographicCoordenateController;
import ec.espe.edu.GeographicInnformationSystem.model.GeographicCoordenate;
import ec.espe.edu.GeographicInnformationSystem.model.UtmCoordenate;
import javax.swing.JOptionPane;

/**
 *
 * @author Domenica
 */
public class frmGeographicCoordenate extends javax.swing.JFrame {

    /**
     * Creates new form frmGeographicCoordenate
     */
    public frmGeographicCoordenate() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtLongitude = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtLatitude = new javax.swing.JTextField();
        btnCalculate = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtShowGeographicCoordinate = new javax.swing.JTextArea();
        btnShow = new javax.swing.JButton();
        txtshowUtmCoordenates = new javax.swing.JTextField();
        btnutmCoordenates = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtutmLatitude = new javax.swing.JTextField();
        txtutmLongitude = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtEnterTheScale = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtCalculateTheScale = new javax.swing.JTextArea();
        btnCalculateScale = new javax.swing.JButton();
        btnSaveScale = new javax.swing.JButton();
        btnShowScale = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Bright", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 102, 0));
        jLabel1.setText("Geographic Coordenates System ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 0));
        jLabel2.setText("╔╩═══════════════════════╩═══════════════════════╩╗");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 0));
        jLabel3.setText("╚╦═══════════════════════╦══════════════════════╦╝");

        jLabel4.setFont(new java.awt.Font("Eras Light ITC", 1, 12)); // NOI18N
        jLabel4.setText("Enter Longitude in cm:");

        txtLongitude.setFont(new java.awt.Font("Eras Light ITC", 0, 12)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Eras Light ITC", 1, 12)); // NOI18N
        jLabel5.setText("Enter Latitude in cm:");

        txtLatitude.setFont(new java.awt.Font("Eras Light ITC", 0, 12)); // NOI18N

        btnCalculate.setFont(new java.awt.Font("Eras Light ITC", 0, 12)); // NOI18N
        btnCalculate.setText("Calculate");
        btnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateActionPerformed(evt);
            }
        });

        txtShowGeographicCoordinate.setColumns(20);
        txtShowGeographicCoordinate.setFont(new java.awt.Font("Eras Light ITC", 0, 12)); // NOI18N
        txtShowGeographicCoordinate.setRows(5);
        jScrollPane1.setViewportView(txtShowGeographicCoordinate);

        btnShow.setFont(new java.awt.Font("Eras Light ITC", 0, 12)); // NOI18N
        btnShow.setText("Show Coordanates");
        btnShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowActionPerformed(evt);
            }
        });

        btnutmCoordenates.setText("UTM Coordenates");
        btnutmCoordenates.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnutmCoordenatesActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Eras Light ITC", 1, 12)); // NOI18N
        jLabel6.setText("UTM Latitude:");

        jLabel7.setFont(new java.awt.Font("Eras Light ITC", 1, 12)); // NOI18N
        jLabel7.setText("UTM Longitude:");

        txtutmLatitude.setFont(new java.awt.Font("Eras Light ITC", 0, 12)); // NOI18N

        txtutmLongitude.setFont(new java.awt.Font("Eras Light ITC", 0, 12)); // NOI18N

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Eras Light ITC", 1, 12)); // NOI18N
        jLabel8.setText("Enter the scale:");

        txtCalculateTheScale.setColumns(20);
        txtCalculateTheScale.setRows(5);
        jScrollPane2.setViewportView(txtCalculateTheScale);

        btnCalculateScale.setText("Calculate Scale");
        btnCalculateScale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateScaleActionPerformed(evt);
            }
        });

        btnSaveScale.setText("Save Scale");
        btnSaveScale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveScaleActionPerformed(evt);
            }
        });

        btnShowScale.setText("Show Scale");
        btnShowScale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowScaleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnSaveScale)
                                .addGap(34, 34, 34)
                                .addComponent(btnCalculateScale)
                                .addGap(150, 150, 150))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(109, 109, 109)
                                        .addComponent(txtEnterTheScale, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(105, 105, 105)
                                        .addComponent(txtutmLongitude, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6))
                                        .addGap(66, 66, 66)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(txtLongitude, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtLatitude, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(txtutmLatitude, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnCalculate)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(btnSave)))
                                .addGap(11, 11, 11)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtshowUtmCoordenates)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(49, 49, 49)
                                        .addComponent(btnShowScale)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(114, 114, 114)
                                    .addComponent(btnutmCoordenates))))
                        .addGap(67, 67, 67))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(166, 166, 166))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(225, 225, 225))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnShow)
                                .addGap(169, 169, 169))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtLongitude, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addComponent(btnCalculate)
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtLatitude, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnShow)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtutmLatitude, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(txtshowUtmCoordenates, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtutmLongitude, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(btnutmCoordenates)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtEnterTheScale, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSaveScale)
                            .addComponent(btnCalculateScale)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(btnShowScale)))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed

        float longitude;
        float latitude;
        int longitudeGrade = 78;
        float minutesLongitude;
        float decimalPartLongitude;
        float wholePartLongitude;
        float secondsLongitude;
        float latitudeGrade = 0;
        float minutesLatitude;
        float decimalPartLatitude;
        float wholePartLatitude;
        float secondsLatitude;
        GeographicCoordenateController geographicCoordenateController = new GeographicCoordenateController();
        GeographicCoordenate geographicCoordenate;

        longitude = Float.parseFloat(txtLongitude.getText());
        latitude = Float.parseFloat(txtLatitude.getText());

        geographicCoordenate = new GeographicCoordenate(longitude, latitude);
        geographicCoordenateController.save(geographicCoordenate);
        minutesLongitude = geographicCoordenateController.calculateMinutesLongitude(longitude);
        decimalPartLongitude = geographicCoordenateController.calculateDecimalPartLongitude(minutesLongitude);
  
        wholePartLongitude = geographicCoordenateController.calculateWholePartLongitude(minutesLongitude, decimalPartLongitude);
        secondsLongitude = geographicCoordenateController.calculateSecondsLongitude(decimalPartLongitude);
        minutesLatitude = geographicCoordenateController.calculateMinutesLatitude(latitude);
        decimalPartLatitude = geographicCoordenateController.calculateDecimalPartLatitude(minutesLatitude);
        secondsLatitude = geographicCoordenateController.calculateSecondsLatitude(decimalPartLatitude);
        wholePartLatitude = geographicCoordenateController.calculateWholaPartLatitude(minutesLatitude, decimalPartLatitude);
        JOptionPane.showMessageDialog(rootPane, "longitude is --> " + longitudeGrade + "° " + secondsLongitude + "' " + wholePartLongitude + "'' " + "O" + "\n" + "latitude is --> " + latitudeGrade + "° " + wholePartLatitude + "' " + secondsLatitude + "'' " + "S");

    }//GEN-LAST:event_btnCalculateActionPerformed

    private void btnShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowActionPerformed
        GeographicCoordenateController geographicCoordenateController = new GeographicCoordenateController();
        txtShowGeographicCoordinate.setText(geographicCoordenateController.read());


    }//GEN-LAST:event_btnShowActionPerformed

    private void btnutmCoordenatesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnutmCoordenatesActionPerformed

        GeographicCoordenateController geographicCoordenateController = new GeographicCoordenateController();
        txtshowUtmCoordenates.setText(geographicCoordenateController.read());
    }//GEN-LAST:event_btnutmCoordenatesActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        float latitude;
        float longitude;

        GeographicCoordenateController geographicCoordenateController = new GeographicCoordenateController();
        GeographicCoordenate geographicCoordenate = null;

        latitude = Float.parseFloat(txtutmLatitude.getText());
        longitude = Float.parseFloat(txtutmLongitude.getText());

        geographicCoordenateController.save(geographicCoordenate);

        JOptionPane.showMessageDialog(rootPane, geographicCoordenate.getName());

    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnSaveScaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveScaleActionPerformed
        float Scale;

        GeographicCoordenateController geographicCoordenateController = new GeographicCoordenateController();
        UtmCoordenate geographicCoordenate = null;

        Scale = Float.parseFloat(btnCalculateScale.getText());

        geographicCoordenateController.save(geographicCoordenate);

        JOptionPane.showMessageDialog(rootPane, geographicCoordenate.getName());


    }//GEN-LAST:event_btnSaveScaleActionPerformed

    private void btnCalculateScaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateScaleActionPerformed
        Float Scale;

        GeographicCoordenateController geographicCoordenateController = new GeographicCoordenateController();
        UtmCoordenate geographicCoordenate;

        Scale = Float.parseFloat(txtEnterTheScale.getText());

        geographicCoordenate = new UtmCoordenate(Scale);

        JOptionPane.showMessageDialog(rootPane, " Transfotmation Scale --> " + Scale);
    }//GEN-LAST:event_btnCalculateScaleActionPerformed

    private void btnShowScaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowScaleActionPerformed
        GeographicCoordenateController geographicCoordenateController = new GeographicCoordenateController();
        txtCalculateTheScale.setText(geographicCoordenateController.read());
    }//GEN-LAST:event_btnShowScaleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmGeographicCoordenate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmGeographicCoordenate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmGeographicCoordenate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmGeographicCoordenate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmGeographicCoordenate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculate;
    private javax.swing.JButton btnCalculateScale;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSaveScale;
    private javax.swing.JButton btnShow;
    private javax.swing.JButton btnShowScale;
    private javax.swing.JButton btnutmCoordenates;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtCalculateTheScale;
    private javax.swing.JTextField txtEnterTheScale;
    private javax.swing.JTextField txtLatitude;
    private javax.swing.JTextField txtLongitude;
    private javax.swing.JTextArea txtShowGeographicCoordinate;
    private javax.swing.JTextField txtshowUtmCoordenates;
    private javax.swing.JTextField txtutmLatitude;
    private javax.swing.JTextField txtutmLongitude;
    // End of variables declaration//GEN-END:variables

}
